// <auto-generated />
namespace UsersGroupsLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MIg2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MIg2));
        
        string IMigrationMetadata.Id
        {
            get { return "202011250746318_MIg2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
