// <auto-generated />
namespace UsersGroupsLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mig5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig5));
        
        string IMigrationMetadata.Id
        {
            get { return "202011250814145_Mig5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
